### ISSUE TITLE
[3rd Week] 11월 17일 minskim 

### ISSUE THREAD

**Issue by Ilisha29** [sproutt/Meju-Blogging-Study#2]
```
스터디원 친구들이 자주 카프카에 대해서 얘기를 했지만 정확히 어떤 것인지 몰랐는데,

업무중에서 테스트 환경 구성을 위해 카프카를 셋팅할 일이 있어서 이번기회에 카프카 및 관련된 개념을 스터디 주제로 정리하게 되었습니다.

잘 못 이해한내용이 있다면 언제든지 피드백 감사드립니다!!
```

## Kafka

카프카란 아파치 재단에서 스칼라라는 언어로 개발한 `오픈소스 메시지 브로커`이다.

카프카 프로젝트의 목표는 실시간 데이터 피드를 관리하기 위해 통일된 높은 처리량, 낮은 지연시간을 지닌 플랫폼을 제공하는 것을 목표로 한다.

목표만 들었을때는 뭐하는지 잘 모르겠다.

그래서 이해를 위해 카프카가 왜 필요로 하게 되었는지에 이해의 중점을 두었습니다.

카프카는 결국 메시징 시스템인데, 카프카가 없을 때는 하나의 서비스가 너무 많은 시스템속에 연결이 되어있는데,

여러 시스템 속에서 각각 서비스가 데이터 처리를 위해 연결(엔드투 엔드)이 되어있다면, n개의 서비스가 있다면 이들간의 

연결관계는 최대 nC2(n콤비네이션2)가 될 것이다.  이러한 복잡한 연결관계를 가진 서비스는 하나의 연결관계가 문제가 생기면

그 둘 서비스에 문제를 일으킬 뿐만 아니라 이문제의 영향이 다른곳까지 끼칠 수 있다.

따라서 여러 서비스간에 주고 받는 메세지를 중앙화해 처리하는 카프카가 필요하게 되었다.

**기존의 아키텍쳐가 가지는 문제점**

- 실시간 트랜잭션 처리와 비동기 처리가 동시에 이뤄지지만 통합된 전송 영역이 없으니 복잡도가 증가

- 데이터 파이프라인 관리의 어려움이 있다. 통합 데이터 분석을 위해 서로 다른 데이터 시스템을 연결해야할 경우가 있는데, 데이터의 포맷이나 처리하는 방법이 다르다면 통합하기가 어렵다. 또한 복잡성으로 인해 두 시스템 간의 데이터가 서로 달라져 데이터의 신뢰도마저 낮아짐

**카프카로 해결하고자 하는 목표**

- 프로듀서와 컨슈머의 분리

- 메시징 시스템과 같이 영구 메시지 데이터를 여러 컨슈머에게 허용

- 높은 처리량을 위한 메시지 최적화

- 데이터가 증가함에 따라 스케일아웃이 가능한 시스템

## 카프카에서 주키퍼

주키퍼란? : 카프카 서버 (+클러스터) 상태를 관리 -> 분산 코디네이터

- 브로커를 모니터링하고, 토픽과 파티션을 관리

- 주키퍼는 카프카 클러스터 내의 브로커들의 리스트를 가지고 있으며 브로커들을 관리하며 카프카는 주키퍼 없이 실행할 수 없음

- 리더 파티션에 장애가 발생시 주키퍼를 통해 새로운 리더 파티션을 선발

- 새로운 토픽 추가, 브로커 장애 및 토픽 삭제 등의 변경 정보를 카프카에 전달

- 주키퍼는 홀수 개의 서버(3,5,7 ...)를 가지고 있어야 한다.

- 주키퍼는 쓰기를 관장하는 리더 서버 1개와 읽기를 관장하는 나머지 팔로워 서버로 구성

**Comment by hyukjin-lee** [comment]
'카프카는 주키퍼 없이 실행할 수 없음' -> 카프카 2.8 인가부터 주키퍼 없어지지 않았나요 ~

**Comment by hyukjin-lee** [comment]
카프카가 시스템간의 디펜던시 결합도를 낮춰준다는 면에서, 인터페이스를 통해 DIP 를 추구하는 OOP 와 비슷하다고 생각이 드네요.
코드레벨이던 시스템레벨이던 원리와 추구하는 방식은 다 비슷비슷한 것 같다는 잡생각을 해봅니다~
