### ISSUE TITLE
[3rd week] 11월 17일 hotheadfactory

### ISSUE THREAD

**Issue by hotheadfactory** [sproutt/Meju-Blogging-Study#4]
[자바의 @Transactional 어노테이션](https://hotheadfactory.com/?p=2219)

더 깊게 공부해서 다른 면접에선 자신있게 말할 수 있어야겠습니다.

**Comment by hyukjin-lee** [comment]
DB lock, Transaction 쪽 도 공부해보시고 Spring @Transactional 어노테이션 동작방식에 대해서도 공부해보시면 좋을 것 같아요~
